const FETCH_PRODUCTS = "FETCH_PRODUCTS";
const UPDATE_PRODUCT = "UPDATE_PRODUCT";
const ADD_PRODUCTS = "ADD_PRODUCTS";
const ADD_PRODUCT = "ADD_PRODUCT";
const DELETE_PRODUCT = "DELETE_PRODUCT";

export default {
  FETCH_PRODUCTS,
  UPDATE_PRODUCT,
  DELETE_PRODUCT,
  ADD_PRODUCTS,
  ADD_PRODUCT
};
